version: "3.9"

services:

  api:
    build: .
    environment:
#      DB_HOST: host.docker.internal
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      ELASTICSEARCH_URI: "http://host.docker.internal:9200"
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      fixtures:
        condition: service_completed_successfully
      es:
        condition: service_healthy
    command: uvicorn src.api:app --host 0.0.0.0 --port 5000 --reload

  fixtures:
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      ELASTICSEARCH_URI: "http://host.docker.internal:9200"
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      es:
        condition: service_healthy
    command: python ./create_data.py

  migrations:
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      ELASTICSEARCH_URI: "http://host.docker.internal:9200"
    depends_on:
      postgres:
        condition: service_healthy
      es:
        condition: service_healthy
    command: alembic upgrade head

  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  es:
#    image: elasticsearch:8.2.2
    image: elasticsearch:7.17.4
    environment:
      discovery.type: "single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: curl -u elastic:elastic -s -f es:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
